spring.application.name=anvay

# Database Connection Settings
spring.datasource.url=jdbc:mysql://localhost:3306/campus_management
spring.datasource.username=root
spring.datasource.password=cts_likhi@15

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=8081

# JWT Configuration
app.jwt.secret=AnvayMultiTenantEventManagementSecretKey2024SuperSecureKey!@#
app.jwt.expiration-ms=86400000

# Flyway - disable auto migration (using JPA ddl-auto=update)
spring.flyway.enabled=false

# Logging
logging.level.com.cts.mfrp.anvay=DEBUG

# Super Admin Credentials (auto-created on startup)
app.superadmin.name=Super Admin
app.superadmin.email=superadmin@anvay.com
app.superadmin.password=Admin@123
